### ISSUE TITLE
Migrate to SciGateway 2.0

### ISSUE THREAD

**Issue by Pasarus** [fiaisis/frontend#236]
We should be based on releases and not a random develop branch on github. So with that in mind, we need to migrate.

https://github.com/ral-facilities/scigateway/releases

**Comment by Dagonite** [comment]
Assume just this line needs changing:
https://github.com/fiaisis/frontend/blob/aa6bc9941a3ed6837075fead22e4d6cbf4e6735e/container/scigateway.dockerfile#L1
