### ISSUE TITLE
Some footer links are dead

### ISSUE THREAD

**Issue by keiranjprice101** [fiaisis/frontend#65]
### Description of the issue

Some footer links will be dead as they default to `/#` These are defined in https://github.com/ral-facilities/scigateway/blob/develop/public/res/default.json

This is when both parent and plugin are deployed.

**Comment by Dagonite** [comment]
Not something I can correct on the frontend. Would need to edit SciGateway's `default.json` for when we are deployed.

**Comment by Dagonite** [comment]
Reopening as this is still an issue.
